verb1 = input("Enter a verb:")
verb2 = input("Enter a verb")
verb3 = input("Enter a verb:")
verb4 = input("Enter a verb")
verb5 = input("Enter a verb:")
verb6 = input("Enter a verb")
verb7 = input("Enter a verb:")
verb8 = input("Enter a verb")
verb9 = input("Enter a verb:")
verb10 = input("Enter a verb")
noun1 = input("Enter a noun: ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
number = input("Enter a number: ")
celebrity = input("Enter the name of a celebrity: ")

MadLibs = f"Welcome to {celebrity} "

print (MadLibs)